// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A class that exposes all available Firebase options.
class DefaultFirebaseOptions {
  /// Returns [FirebaseOptions] for the current platform based on environment.
  static FirebaseOptions get currentPlatform {
    // Read from environment or use defaults for Reboot Rajasthan project
    return web;
  }

  /// Web Firebase options for Reboot Rajasthan project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForRebootRajasthanProject123456789',
    appId: '1:123456789:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'reboot-rajasthan',
    authDomain: 'reboot-rajasthan.firebaseapp.com',
    storageBucket: 'reboot-rajasthan.appspot.com',
    measurementId: 'G-DEMO123456',
  );

  /// Android Firebase options for Reboot Rajasthan project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForRebootRajasthanAndroid123456789',
    appId: '1:123456789:android:abcdef1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'reboot-rajasthan',
    storageBucket: 'reboot-rajasthan.appspot.com',
  );

  /// iOS Firebase options for Reboot Rajasthan project
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForRebootRajasthanIOS123456789',
    appId: '1:123456789:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'reboot-rajasthan',
    storageBucket: 'reboot-rajasthan.appspot.com',
    iosClientId: '123456789-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.saafsurksha.app',
  );

  /// macOS Firebase options for Reboot Rajasthan project
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForRebootRajasthanMacOS123456789',
    appId: '1:123456789:macos:abcdef1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'reboot-rajasthan',
    storageBucket: 'reboot-rajasthan.appspot.com',
    iosBundleId: 'com.saafsurksha.app',
  );
}
